
// DRY action types
export const PRODUCTS_LOAD_PROGRESS:'PRODUCTS_LOAD_PROGRESS' = 'PRODUCTS_LOAD_PROGRESS';
export const PRODUCTS_LOAD_SUCCESS:'PRODUCTS_LOAD_SUCCESS' = 'PRODUCTS_LOAD_SUCCESS';

//Filters action types
export const FILTERS_CHANGED:'FILTERS_CHANGED' = 'FILTERS_CHANGED';

